AF-43433 solve JavassistMockClassLoader issue with ADocument Mock
Add PowerMock properties because of:
java.lang.IllegalAccessError: class com.aspose.pdf.ADocument cannot
access its superinterface com.aspose.pdf.l7j (com.aspose.pdf.ADocument
is in unnamed module of loader
org.powermock.core.classloader.javassist.JavassistMockClassLoader
@16412616; com.aspose.pdf.l7j is in unnamed module of loader 'app')